### PR TITLE
Fix josua: add validate email lock orientation

### PR DESCRIPTION
**Pull request by josuastg**
# Description, Motivation and Context 
add validate email
lock orientation

# Link to the resources (mockups, change description)  
https://trello.com/c/Cs5XmWhD

# What is the destination branch of this PR?
development

# Screenshots [Mandatory]
image
image

### CODE REVIEW

**Review by PrStWn — APPROVED** [review]
LGTM! wkwkkk

**Comment by josuastg** [comment]
> LGTM! wkwkkk

ampun suhu @PrStWn !!

**Comment by PrStWn** [comment]
> > LGTM! wkwkkk
> 
> ampun suhu @PrStWn !!

wkwkwkkkkkk

**Comment by PrStWn** [comment]
awkkwkwkkkkk

**Pull request merged**
